### ISSUE TITLE
Display informations (count, repartition, ...) of all visible points displayed in the brush

### ISSUE THREAD

**Issue by jlestel** [keplergl/kepler.gl#1208]
I've added on new panel on the left in order to display informations about visible points displayed on the map.

Idealy, I would want to get only points visible in the brush (or if this is not achievable on the whole map).

I'm looking for a way to do it, but before going too far, do you think it's achievable now?

If so, how do you advise me to proceed?

**Comment by heshan0131** [comment]
Hi @jlestel do you have experience working with deck.gl? Unfortunately it's not very easy to do for kepler.gl. Because kepler.gl does filtering on GPU (brushing, slider, time animation) for performance. It would require some work to can a callback directly hook into deck.gl's GPU filtering module, and modify the module to send the count back...

**Comment by jlestel** [comment]
Hi @heshan0131 I had no experience with deck.gl yet but thank to your answer I'll try to do the right things in the right places.

I will keep you informed if I succeed and it seems to you that this is a relevant element for the evolution of the products.
