### ISSUE TITLE
403 Forbidden Error: Not able to render base map styles 'Light' or 'Muted Light' when Label Map Layer is selected

### ISSUE THREAD

**Issue by magamonsta** [keplergl/kepler.gl#121]
When running a local deployment of kepler.gl (also problem happened when doing a Vis Academy embed kepler.gl tutorial), the original Dark Base Map Style loads perfectly fine with my mapbox token, but when I try to switch the Base Map Style to 'Light' or 'Muted Light' the map doesn't render and I get loads of error.

The error doesn't appear when I try to load 'Muted Dark'.

Here is a screenshot of the map that loads when you select Light or Muted Light, it is not the correct basemap and if you zoom in much further even the simple country outline disappears and no labels or borders appear. I have also attached a screenshot of the console errors. I am able to load data no problem and am able to load custom styles no problem.
![screenshot 8](https://user-images.githubusercontent.com/38330505/41543246-95715648-72e4-11e8-8b6d-643c628b292c.png)
![screenshot 9](https://user-images.githubusercontent.com/38330505/41543249-95b30a98-72e4-11e8-97a5-09ebf5f66d51.png)

**Comment by weatherlym** [comment]
i'm having the same problem with the most recent version running from demo-app

Map Style Light and Muted Light won't load if the Label Layer is selected

**Comment by magamonsta** [comment]
any movement on this error?

**Comment by stevenroussey-desiclabs** [comment]
Just tried this today and the map fails to load with permission errors. It is "fixed" if I use the token in the example rather than my own.

**Comment by DanielM235** [comment]
Experiencing the same issue with v1.1.10

**Comment by daaain** [comment]
The issue is that the Light theme is referencing fonts from the Uber style, but if you use your own token (and not the Uber one from the example) these fonts won't load due to permission error (hence the 403s) which then breaks the map style.

The solution to this would be forcing Uber map styles to always use the Uber Mapbox token, even if a custom token is set. Otherwise it's not possible to have a custom style working alongside the built in ones.
