### ISSUE TITLE
[Bug] No Color Scale quantize

### ISSUE THREAD

**Issue by PiRomant** [keplergl/kepler.gl#1498]
**Describe the bug**
No Color Scale quantize without Filter By Count Percentile

**To Reproduce**
https://kepler.gl/demo/map?mapUrl=https://dl.dropboxusercontent.com/s/qxxr1hh3rgjukm2/keplergl_qxafuag.json
Use Filter By Count Percentile at 100%

**Screenshots**
![Screenshot of kepler gl (2)](https://user-images.githubusercontent.com/29551044/119838098-5676ec80-bf2d-11eb-9ff0-dcc8f52ced96.jpg)
![Screenshot of kepler gl (3)](https://user-images.githubusercontent.com/29551044/119838109-57a81980-bf2d-11eb-9786-6e312900d3e0.jpg)

**Desktop (please complete the following information):**
Windows 10
Chrome 91.0.4472.77

**Comment by heshan0131** [comment]
This is not a bug, it is showing an anomaly in your data

Quantize is distributed color based on linear scale. Because you have 1 hexagon with significantly large number of points, it only renders that specific one red, the rest white. When filter OUT that one by applying 99 percentile, the color is redistributed to high light lower percentiles


__Quantize color scale with 100% percentile__
<img width="1004" alt="Screen Shot 2021-06-07 at 4 30 34 PM" src="https://user-images.githubusercontent.com/3605556/121100025-d1ea6080-c7ad-11eb-91a5-b0b7f0190686.png">

<img width="179" alt="Screen Shot 2021-06-07 at 4 29 22 PM" src="https://user-images.githubusercontent.com/3605556/121100054-dd3d8c00-c7ad-11eb-89ec-45e7f986343f.png">

__Quantize color scale with 99% percentile__
<img width="1016" alt="Screen Shot 2021-06-07 at 4 34 32 PM" src="https://user-images.githubusercontent.com/3605556/121100227-402f2300-c7ae-11eb-9315-54d1254ba60f.png">
