### ISSUE TITLE
[Bug] Stagnant response after dataset loaded to demo site.  Multiple browsers and computers tried - no success.

### ISSUE THREAD

**Issue by runsalot87** [keplergl/kepler.gl#1945]
When uploading a dataset to Kepler.gl/demo, the dataset load reaches 100% and says "done" below the status bar, but nothing happens after this.  Have tried on multiple computers and browsers with the same results.  Wondering if something needs to be reset on the kepler server side.  This was working fine last week.

**Comment by runsalot87** [comment]
@heshan0131 Can you please assist?

**Comment by iocfinc** [comment]
I can also replicate the issue, which only affects some files from what I can tell.

I was able to upload some datasets with Polygons, Points and H3 items. However, some datasets got stuck on upload (Done but not loaded as described by @runsalot87), which also contain Points and H3 items.

If anything, the differentiation I can see is the file size difference. The files that got stuck for me were a JSON from saved map (80MB) and a CSV file that was (68MB). I originally thought I can recreate the map from the loose datasets (since the JSON save file was getting stuck), but the CSV file was getting stuck so I also cannot work around the issue.
