### ISSUE TITLE
MapLibre support

### ISSUE THREAD

**Issue by birkskyum** [keplergl/kepler.gl#2460]
**Is your feature request related to a problem? Please describe.**
There is currently no way to use MapLibre with kepler.gl, thus demanding users to find a mapbox api key in order to use this tool, and limiting the options for using kepler.gl in an air-gapped environment.

**Describe the solution you'd like**
Since Kepler.gl and Deck.gl are free and open source, it would be great to have a way to use kepler.gl with free and open source MapLibre, similar to how react-map-gl and deck.gl allow for it.

**Describe alternatives you've considered**
Currently, only solution is for users to fork kepler.gl and swap mapbox-gl with maplibre-gl.

**Comment by birkskyum** [comment]
Great to hear. In the past I've been replacing mapbox directly with maplibre. If the desire for kepler.gl is to have both mapbox/maplibre as user-selected options through i.e. a peerDependency, that goes a bit beyond what I've been doing so far.

**Comment by ibgreen** [comment]
Good point. 

Longer term there is indeed a desire to allow for pluggable base map renderers including the new vis.gl bindings for [Google Maps](https://visgl.github.io/react-google-maps/). We might even want users to be able to switch between various basemap renderers at run-time. 

But that will require a bigger effort. 

So for now I think yes, it makes total sense to make maplibre the default basemap, and since this could affect some users, a major release like 3.0 would be a good release to make this "breaking" change.

(Of course it would be good if we made it easy for users to in their custom builds replace maplibre with mapbox, if that doesn't require too much extra work).
