### ISSUE TITLE
Publish kepler.gl for jupyter notebook

### ISSUE THREAD

**Issue by heshan0131** [keplergl/kepler.gl#331]
**Feature**
Publish a kepler.gl for jupyter python package to load kepler.gl inside jupyter notebook

<img width="940" alt="screen shot 2018-11-16 at 2 06 51 pm" src="https://user-images.githubusercontent.com/3605556/51218156-fd6c0800-18df-11e9-8114-e3d842a0291f.png">

**Solution**
![kepler gl jupyter notebook](https://user-images.githubusercontent.com/3605556/51218335-c813ea00-18e0-11e9-8988-05e6913e399c.png)

- Create a kepler.gl build to embed js and css into a single html
- Create a jupyter notebook python package to load keplergl.html inside an iframe
- Publish kepler.gl for jupyter
- Allow adding data and config via python API

**Appendix**

[Kepler.gl Jupyter Integration Slides](https://docs.google.com/presentation/d/1wMWhnAr6oLO4ldG4aWq3hgUImsTxJeG77D93x-D_8dM/edit?usp=sharing)

**Comment by rmanisthebest** [comment]
May i ask any notebook template or example for this feature?

**Comment by heshan0131** [comment]
This work is still in progress

**Comment by ibgreen** [comment]
Links to deck.gl Python RFC
* https://github.com/uber/deck.gl/issues/2746
* https://github.com/uber/deck.gl/issues/2747

**Comment by briantcl** [comment]
1) user testing
2) need marketing plan for the release
3) medium post/ marketing release (TBD)

Target release date: next sprint

**Comment by briantcl** [comment]
Launch Plan:
1) medium post
2) Share the medium post url through linkedin, twitter

**Comment by murari-goswami** [comment]
Any date for release ?

**Comment by emiliomartin84** [comment]
Any update about the release date?

**Comment by murari-goswami** [comment]
Hi Briantcl, any update on the launch plan ?

**Comment by chintanp** [comment]
Are there plans to support Jupyter lab? I am able to test it with jupyter notebook and it works. :)

**Comment by wasauce** [comment]
FYI - https://medium.com/vis-gl/introducing-kepler-gl-for-jupyter-f72d41659fbf - I hadn't seen this and was thinking it wasn't released yet. Very exciting! Thank you!

**Comment by saulshanabrook** [comment]
I have [hacked together](https://github.com/saulshanabrook/kepler.gl/commit/9a908b3292b01f0bd21ea739c742bea75fe7e216) some JupyterLab support. There is currently a JuptyerLab plugin in this repo, but it isn't being built currently, as far as I can tell.

To use this with JupyterLab 1.0:

```bash
conda create -n kepler-jupyterlab -c conda-forge jupyterlab=1.0.0
conda activate kepler-jupyterlab
pip install ipywidgets keplergl
jupyter labextension install @jupyter-widgets/jupyterlab-manager
git clone git@github.com:saulshanabrook/kepler.gl.git
cd kepler.gl/bindings/kepler.gl-jupyter/js
yarn
env MapboxAccessTokenJupyter=<YOUR_TOKEN> npx babel lib --out-dir babel
jupyter labextension install .
```

It seems to work OK:

```python
from keplergl import KeplerGl 
map_1 = KeplerGl(height=500)
map_1

# new cell
import pandas as pd
df = pd.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})

map_1.add_data(data=df, name='cities')
```


<img width="965" alt="Screen Shot 2019-07-02 at 1 34 20 PM" src="https://user-images.githubusercontent.com/1186124/60533655-1de12080-9cce-11e9-9005-b3d2a15fa6db.png">


The changes I made were:
* Build version of JS files that doesn't include JSX syntax, using babel. Also turn off some of babels plugins, so that ES6 imports are preserved
* Change some imports so they build properly with JL
* Update the `@jupyter-widgets/base` dependency so it matches the one in JL. There are probably breaking changes in here, but I am not sure if they matter for this use case.

**Comment by heshan0131** [comment]
@saulshanabrook Thank you so much for this!! I will implement your changes and test it

**Comment by heshan0131** [comment]
`keplergl==0.1.0` and `keplergl-jupyter@0.1.0` can now be installed on jupyter Labs
(Python 3 tested)

https://github.com/keplergl/kepler.gl/pull/764

**Comment by heshan0131** [comment]
Add install instruction for Jupyter Lab
https://github.com/keplergl/kepler.gl/tree/master/bindings/kepler.gl-jupyter#installation
Close this for now 🥂
