### ISSUE TITLE
Provide backend connector

### ISSUE THREAD

**Issue by heshan0131** [keplergl/kepler.gl#409]

**Comment by maartenbreddels** [comment]
Hi,

it is not clear to me what you mean by backend connector, does this include the use case 'server side aggregation'?

I'm the main author of [Vaex](https://github.com/vaexio/vaex) which is an out of core dataframe library for Python that allows aggregation in the order of ~1 billion rows/second.
I'm focussing on visualization in the Jupyter notebook lately, and since I also write ipyvolume (a jupyter-
widget 3d library for Python) I also combined them, to show aggregated geo-data [Example](https://giphy.com/gifs/vaex-Wpm2nb4lDVOWfciUFK)

But I think if I want to show geo-data, it would be better to use kepler.gl. However, it seems to me that I can only let kepler.gl do the aggregation, I cannot provide pre-aggregated data. Is that correct, and are there plans to change this?

Regards,

Maarten

**Comment by seanosterday** [comment]
Heads up: this one says it's delivered on the roadmap but evidently hasn't been started.

**Comment by heshan0131** [comment]
#947
