### ISSUE TITLE
Increase upload dataset limit

### ISSUE THREAD

**Issue by heshan0131** [keplergl/kepler.gl#410]
-   Upload file larger than 250 MB using the binary buffer

-   Re-construct string or JSON from the binary buffer

**Comment by stevenroussey-desiclabs** [comment]
Perhaps stream instead? 

http://oboejs.com/

**Comment by MorganGellert** [comment]
Piggybacking on this thread because it seems relevant but I can open a separate issue if needed. The remote map upload fails on json files larger than 50MB because of this error: https://github.com/d3/d3-fetch/issues/34 A solution is to cut out `d3-fetch` and use just `fetch` and `FetchSteam` instead (similar to @stevenroussey-privicy 's suggestion).

**Comment by UnityEQ** [comment]
Any updates on this!! Can't map national zips because the geojson is too big. (1.2gb). National Zip boundaries are about 450mb without appended data.

**Comment by heshan0131** [comment]
#1156
