### ISSUE TITLE
Data-driven styling with expressions

### ISSUE THREAD

**Issue by TrantorM** [keplergl/kepler.gl#493]
[Mapbox GL JS expressions](https://docs.mapbox.com/help/tutorials/mapbox-gl-js-expressions/) is a very nice way to do data-driven styling based on custom data properties and zoom level. In my case I need it to draw a choropleth map based on a calculation that uses multiple properties.

Do you plan to introduce expressions in the future? I couldn't find any remarks in the roadmap regarding this.

Desired solution: The value of a style property should be able to take an expression instead of a simple feature property.

**Comment by heshan0131** [comment]
Hi @TrantorM I understand your use case. Personally I find the expression like `10, ['/', ['-', 2017, ['number', ['get', 'Constructi'], 2017]], 30],`  in data-driven styles little hard to understand.  They have their limitations of course because everything needs to be folded into a JSON

We are planning to add support to edit the underlying dataset using the big table editor. Something like Carto's [Data View](https://carto.com/help/building-maps/adding-rows-and-columns-in-the-data-view/) So you will be able to create a new column in your dataset based on the calculation of other columns. Then use that column to assign color / radius/ height.

We have a [Data Manipulation](https://github.com/uber/kepler.gl/wiki/Kepler.gl-2019-Roadmap#data-manipulation) part in our roadmap. Joining and editing data types will be supported. When we get to it, we can also add support to add a column base on mathematical expressions. 

**That is if more people upvoted your issue**

**Comment by TrantorM** [comment]
Hi @heshan0131 Thx for the response. I am very excited about the advances in data manipulation (especially in joining) and data-driven styling.

Some thoughts on the topic:
- For my use case I want to use two selectors that chose two properties and calculate the ratio of them, which is the base for the choropleth. With e.g. 12 columns, there are 66 combinations, or 132 considering the inverse ratio. A handy selection tool is in this case desirable.
- It may be easier to implement selectors or something similar in mapbox kind expressions.
- The beauty of expressions is that it offers a lot of flexibility. But I agree, the downside is that it's not that intuitive to use, especially as the formula or function gets more complex. However, it isn't uncommon. QGIS for example also uses [expressions](https://docs.qgis.org/3.4/en/docs/pyqgis_developer_cookbook/expressions.html) e.g. in the [field calculator](https://docs.qgis.org/2.8/en/docs/user_manual/working_with_vector/field_calculator.html).

**Comment by macrigiuseppe** [comment]
this can be done dow through columnar ui feature in [studio.unfolded.ai](https://studio.unfolded.ai).
