### ISSUE TITLE
Data Preview does not show all columns

### ISSUE THREAD

**Issue by tusheet** [keplergl/kepler.gl#523]
**Describe the bug**
The data preview shows only a few columns irrespective of how many columns are there in the data.

**To Reproduce**
1. Go to https://kepler.gl/demo/earthquakes
2. Click on 'Show data tables' in the layers tab
3. Scroll to the left, you can only see till column 'Gap'. Close the data preview
4. Go to the Interactions tab
5. Click on Add Tool Tip Box & there are other columns like Distance, RMS etc that cannot be seen in the data preview

**Expected behavior**
All columns should be visible in the data preview or some intimation that only a few columns are being displayed

**Desktop (please complete the following information):**
 - OS: macOS Sierra Version 10.12.4
 - Browser Chrome Version 74.0.3729.157

**Comment by heshan0131** [comment]
@macrigiuseppe seems like the modal changes broke the data table horizontal scrolling

**Comment by macrigiuseppe** [comment]
I see the issue. I spent some time going back in time with git and check if the same issue appears with our previous implementation and i can see the same problem with our previous implementation when resizing the window.
Since I already planned on replacing react-data-grid (#499), the component used to display the table, I am gonna work on it and fix this bug. 

Tracking the work here #553

**Comment by macrigiuseppe** [comment]
This is fixed in #629
