### ISSUE TITLE
Data Security in Kepler.gl

### ISSUE THREAD

**Issue by arnabbiswas1** [keplergl/kepler.gl#730]
**This is not a bug. But a query**. Since, the slack channel is not actively monitored, thought of posting it here.

I want to use kepler.gl initially on Jupyter Notebook and probably on on-premise server in future (if needed).  The data to be used is proprietary and MUST not be exposed/shared outside the organization. I have few questions related to data security:

1.  Does kepler.gl client/server has any tracking (e.g. google analytics) enabled? The idea is to collect just the usage information on the client/server instance of kepler.gl and send it to remote server.
2. Does kepler.gl client on the Jupyter  or the kepler.gl server instance needs internet connection to work? If yes, why?
3. Does kepler.gl client on the Jupyter  or the kepler.gl server instance sends any data in any form (used for visualization. In my case the proprietary data) to the remote server?

I understand that kepler.gl is an open source software under MIT license. But, as per my knowledge, MIT license doesn't prohibit any kind of collection of data from the user who is using the software (kepler.gl). And hence this query.

**Comment by macrigiuseppe** [comment]
hello @arnabbiswas1,
Thank you for using Kepler.gl.

before answering your questions, I want to make sure you understand Kepler.gl is a full client-side application which doesn't have nor require server-side components. All data you load in Kepler.gl are only available on your machine and only to you (more info: https://lfprojects.org/policies/privacy-policy/, __project-specific uses__ section).

1. We need to distinguish between two cases:
  -  https://kepler.gl demo site: if you are trying to use Kepler.gl on our demo site, we collect usage information. Only meta-information is collected through google analytics, e.g. user action (how many clicks on settings, etc...). No actual data is exposed.
  - kepler.gl as library/on-premise: we do not collect any information.
2. Kepler.gl requires an internet connection in order to fetch map tiles from Mapbox
3. No

Hope my answer satisfy your inquiry.

**Comment by arnabbiswas1** [comment]
@macrigiuseppe Thank you for confirming. 

Also, thanks to uber for creating such a wonderful tool.
