### ISSUE TITLE
[Bug][Jupyter Widget] Can't see tooltip data points 

### ISSUE THREAD

**Issue by qxlsz** [keplergl/kepler.gl#794]
**Describe the bug**
If I understand correctly the tooltip should show whatever columns I select from my data source

**To Reproduce**
1. load kepler
2. Add data & config
3. Export map

**Expected behavior**
It needs to show columns added to tooltip 

**Screenshots**
![image](https://user-images.githubusercontent.com/4540836/66963250-16991500-f028-11e9-8e16-79496c407978.png)

**Environment (please complete the following information):**
 - Python version: Python3.6
 - keplergl Widget version [e.g. 0.1.0]

**Additional context**

**Comment by qxlsz** [comment]
I can easily add co ordinates by turning on co ordinates. But it's not clean when it moves with my cursor. I only wanted to see when I select the data points.

**Comment by qxlsz** [comment]
But I can see in tooltip for sample data viz 
![image](https://user-images.githubusercontent.com/4540836/66963481-a8a11d80-f028-11e9-854e-5987e436bb8e.png)


Is there a specific format they should be in to show up ?

**Comment by qxlsz** [comment]
Agh. It works with points. It doesn't work with hexbin's.  But can we get it in hexbins also please?

**Comment by xiaofanliang** [comment]
Has this been solved? I used the cluster view and this is an issue because the tooltip only shows the count / average value of the cluster even when the cluster only contains one data point. I was hoping that when zoomed in enough (when the cluster only contain one point, the tooltip can show the information of that point rather than the summary statistics of the cluster.
