### ISSUE TITLE
[Bug] Gaps & overlaps while rendering dataset with hex

### ISSUE THREAD

**Issue by bkowshik-rapido** [keplergl/kepler.gl#887]
### Describe the bug
I see empty gaps and rendering issues while working with datasets with `hex`. Ex: Below is a sample dataset I have having issues with.

- https://gist.github.com/bkowshik-rapido/0f5a5006326d501c1b5a477005bb6254

### To Reproduce
Upload the above dataset onto Kepler.

### Expected behavior
The hex's should be laid out without the missing gaps or the overlaps with neighboring cells.

### Screenshots
<img width="1680" alt="Screenshot 2020-01-05 at 3 20 28 AM" src="https://user-images.githubusercontent.com/58680555/71772055-5fe36b80-2f6a-11ea-9bb6-e4f1714762d0.png">

Tested on Mac, Firefox `v71.0`

**Comment by Pessimistress** [comment]
@heshan0131 I don't see this issue in deck.gl 7.3 or 8.0. Is it possible to upgrade the dependency in kepler?

**Comment by heshan0131** [comment]
I think the issue is related to using `h3Distance` and how kepler.gl updates viewport across the globe.

Here are things happening in kepler:

- Initial map, viewport set to San Francisco:  `latitude: 37.7749295,  longitude: -122.4194155`
- Upload csv. kepler.gl create a h3 layer and pass along the deck.gl. viewport is still in SF
- deck create h3 layer, set centerHex to be in sf
- kepler.gl determined dataset is centered in Hyderbad (17.454774299526278 78.36112961135476) and updated viewState
- deck.gl sent updated viewState to h3-hexagon-layer, compare new centerHex with previous on using [h3Distance()](https://github.com/uber/deck.gl/blob/master/modules/geo-layers/src/h3-layers/h3-hexagon-layer.js#L164). h3Distance returns a negative number `-1.220629759` because the 2 points are too far apart. Due to its own [limitation](https://github.com/uber/h3-js#module_h3.h3Distance). The distance comparison failed. h3 layer exits `_updateVertices` 

- This falls into an unfortunate loop, because `centerHex` will never gets updated. and distance comparison will always fail...
