### ISSUE TITLE
3D/Height option not working with polygon maps

### ISSUE THREAD

**Issue by annmorris** [keplergl/kepler.gl#888]
When I click on the 3D map option, the height drop down does not open up to allow me to select a field to base height on.

1. I uploaded a file from my computer: pluto_bk.csv
2. This produced a 2D polygon map. I changed the fill colors based on the "NumFloors" field.
3. I then clicked on the 3D Map option in the upper right hand corner.
4. I clicked on the height option (triple dots at right), but the list of fields remained grayed out. The map never showed any 3D effects, based on a field or not based on a field.

I experienced this using Chrome on a Mac desktop. I tried several other files, all under what I thought was the 250 MB limit.

**Comment by annmorris** [comment]
Recreating input file as .xlsx since Github wouldn't allow me to attach a .csv.
pluto_bk.xlsx

**Comment by annmorris** [comment]
[pluto_bk.xlsx](https://github.com/keplergl/kepler.gl/files/4022803/pluto_bk.xlsx)

**Comment by heshan0131** [comment]
To show the height option, the `fill color` toggle has to be turned on. Because height can only be applied to solid polygons (not path). 

<img width="274" alt="Screen Shot 2020-01-10 at 8 08 06 PM" src="https://user-images.githubusercontent.com/3605556/72198616-01444480-33e5-11ea-9622-f1a6fb6b92f9.png">

However, ui side, it's confusing to completely hide an option behind another option. I am going to add a `disabled` state to the height, it will still be there, but disabled

https://github.com/keplergl/kepler.gl/pull/897

**Comment by heshan0131** [comment]
The fix is landed in demo, please check
